// Generated by dts-bundle v0.4.2
// Dependencies for this module:
//   ../../../gulp-help

declare module 'tst' {
    
    export { PathConfiguration } from 'tst/Configuration/PathConfiguration';
    import { GuildConfiguration } from 'tst/Configuration/GuildConfiguration';
    import { GulpHelp } from 'gulp-help';
    export function guild(gulp: GulpHelp, configuration: GuildConfiguration): void;
}

declare module 'tst/Configuration/PathConfiguration' {
    export class PathConfiguration {
    
    }
}

declare module 'tst/Configuration/GuildConfiguration' {
    export class GuildConfiguration {
    
    }
}

